# Generated by Django 6.0.3 on 2026-04-25 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='transaction_pin',
        ),
        migrations.AddField(
            model_name='customer',
            name='pin',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
