# Generated by Django 6.0.3 on 2026-04-25 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_customer_transaction_pin_customer_pin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='pin',
            field=models.CharField(max_length=128),
        ),
    ]
