# Generated by Django 6.0.3 on 2026-04-25 19:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_customer_pin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='pin',
        ),
        migrations.AddField(
            model_name='customer',
            name='transaction_pin',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='fixeddeposit',
            name='duration',
            field=models.IntegerField(help_text='Duration in months'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='reference_id',
            field=models.CharField(default=uuid.uuid4, max_length=100, unique=True),
        ),
    ]
