# Generated by Django 6.0.3 on 2026-05-07 08:26

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_customer_pin_customer_transaction_pin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixeddeposit',
            name='interest_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('6.50'), max_digits=5),
        ),
        migrations.AddField(
            model_name='fixeddeposit',
            name='maturity_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='fixeddeposit',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('MATURED', 'Matured'), ('CLOSED', 'Closed')], default='ACTIVE', max_length=10),
        ),
    ]
